// Generated by scripts/sync-research-vault.mjs. Do not edit by hand.
export const researchVault = {
  "sourceUpdatedAt": "2026-07-17",
  "stages": [
    {
      "id": "ml-workflow-evaluation",
      "index": "B",
      "title": "Machine Learning Workflow & Evaluation",
      "summary": "使用 scikit-learn Pipeline、cross-validation、baseline 与 error analysis 进行可信的传统机器学习实验。",
      "status": "Current",
      "outcome": "已开始：Pipeline、cross-validation 与 holdout test。",
      "updatedAt": "2026-07-27",
      "href": "/research-trail"
    },
    {
      "id": "foundations",
      "index": "A",
      "title": "Environment, Python & Math Foundations",
      "summary": "通过可运行的小实验恢复 Python、NumPy、调试、数学与 optimization 的最小直觉。",
      "status": "Completed",
      "outcome": "已完成 NumPy 线性回归、训练稳定性、模型选择、数据代码阅读与不平衡二分类评估；能追踪基础 ML pipeline 并识别 evaluation leakage。",
      "updatedAt": "2026-07-27",
      "href": "/research-trail"
    }
  ],
  "events": [
    {
      "id": "evt-20260715-numpy-linear-regression-created",
      "occurredAt": "2026-07-15",
      "type": "artifact_created",
      "title": "创建 NumPy 最小线性回归学习实验",
      "summary": "建立 Shape、预测、MSE 与 gradient descent 的可运行学习实验。",
      "stageId": "foundations"
    },
    {
      "id": "evt-20260716-numpy-linear-regression-verified",
      "occurredAt": "2026-07-16",
      "type": "experiment_completed",
      "title": "完成线性回归 learning-rate 对照实验",
      "summary": "验证正常学习率下 loss 下降，并观察过大学习率导致的训练发散。",
      "stageId": "foundations"
    },
    {
      "id": "evt-20260716-train-validation-test-started",
      "occurredAt": "2026-07-16",
      "type": "artifact_created",
      "title": "开始 Train / Validation / Test 学习实验",
      "summary": "开始实践模型选择、underfitting、overfitting 与泛化评估。",
      "stageId": "foundations"
    },
    {
      "id": "evt-20260717-train-validation-test-completed",
      "occurredAt": "2026-07-17",
      "type": "experiment_completed",
      "title": "完成 Train / Validation / Test 模型选择实验",
      "summary": "用 validation MSE 选择 degree=5，并验证最低 train MSE 不等于最佳泛化模型。",
      "stageId": "foundations"
    },
    {
      "id": "evt-20260717-multifeature-vectorized-gradient-completed",
      "occurredAt": "2026-07-17",
      "type": "experiment_completed",
      "title": "完成多特征向量化 Gradient Descent 实验",
      "summary": "完成 X @ w + b 的多参数训练，并用 feature scale 对照解释梯度 shape 对齐与数值发散。",
      "stageId": "foundations"
    },
    {
      "id": "evt-20260724-numpy-pandas-data-reading-completed",
      "occurredAt": "2026-07-24",
      "type": "lesson_completed",
      "title": "完成 NumPy 与 Pandas 数据代码阅读课程",
      "summary": "掌握常用数据操作的阅读地图，能追踪 X-y 对齐、axis 聚合、类别统计、缺失值检查与填补。",
      "stageId": "foundations"
    },
    {
      "id": "evt-20260727-classification-metrics-leakage-completed",
      "occurredAt": "2026-07-27",
      "type": "experiment_completed",
      "title": "完成 Binary Classification Metrics 与 Data Leakage 实验",
      "summary": "完成 baseline 与 logistic classifier 对比，能用 F1、validation threshold 与 train-only normalization 判断评估是否可信。",
      "stageId": "foundations"
    },
    {
      "id": "evt-20260727-stage-b-ml-workflow-entered",
      "occurredAt": "2026-07-27",
      "type": "stage_entered",
      "title": "进入 Stage B：Machine Learning Workflow 与 Evaluation",
      "summary": "从手写 NumPy 流程进入 scikit-learn Pipeline、cross-validation、模型比较与可靠评估。",
      "stageId": "ml-workflow-evaluation"
    },
    {
      "id": "evt-20260728-b01-pipeline-completed",
      "occurredAt": "2026-07-28",
      "type": "experiment_completed",
      "title": "完成 B-01：scikit-learn Pipeline、Cross-Validation 与 Holdout Test",
      "summary": "完成 Pipeline/CV/holdout test 流程，理解 C 的逆正则化与 C=0.001 的极端退化现象。",
      "stageId": "ml-workflow-evaluation"
    }
  ],
  "tree": [
    {
      "id": "ai-cv-research",
      "label": "AI / CV 研究能力",
      "type": "root",
      "status": "active"
    },
    {
      "id": "ai-cv-foundations",
      "label": "AI / CV 基础",
      "type": "track",
      "status": "active",
      "parent": "ai-cv-research",
      "learningRole": "primary-research-track"
    },
    {
      "id": "numpy-ml-foundations",
      "label": "NumPy 与机器学习基础",
      "type": "topic",
      "status": "active",
      "parent": "ai-cv-foundations"
    },
    {
      "id": "numpy-linear-regression",
      "label": "实验：NumPy 最小线性回归",
      "type": "experiment",
      "status": "completed",
      "parent": "numpy-ml-foundations",
      "learningRole": "primary-research-track",
      "goal": "用 NumPy 跑通一元线性回归，理解 shape、MSE、gradient descent 与 learning rate。",
      "summary": "完成收敛与发散对照，能解释负梯度更新和学习率过大导致的发散。",
      "readinessCriteria": [
        "能解释 (3,) 与标量 broadcasting",
        "能说明 MSE、dw、db 与 negative gradient update 的关系",
        "能根据 loss 曲线判断正常收敛与 learning-rate 发散"
      ]
    },
    {
      "id": "train-validation-test-model-selection",
      "label": "实验：Train / Validation / Test 模型选择",
      "type": "experiment",
      "status": "completed",
      "parent": "numpy-ml-foundations",
      "learningRole": "primary-research-track",
      "goal": "用多项式模型选择理解 train、validation、test 的分工，以及 underfitting / overfitting。",
      "summary": "用 validation MSE 选择 degree=5，并验证最低 train MSE 不等于最佳泛化模型。",
      "readinessCriteria": [
        "能说明为何用 validation 而非 test 选择 hyperparameter",
        "能从 train / validation MSE 曲线识别 underfitting 与过拟合迹象",
        "能说明最低 train MSE 不一定对应最佳泛化模型"
      ]
    },
    {
      "id": "multifeature-vectorized-gradient",
      "label": "实验：多特征线性回归与向量化 Gradient Descent",
      "type": "experiment",
      "status": "completed",
      "parent": "numpy-ml-foundations",
      "learningRole": "primary-research-track",
      "goal": "用 NumPy 训练多特征线性回归，理解向量化 gradient descent 与参数梯度的 shape 对齐。",
      "summary": "完成多参数梯度训练与 feature scale 对照，能解释 `X.T @ residual`、梯度 shape 对齐和尺度导致的训练发散。",
      "readinessCriteria": [
        "能说明 X、w、dw 与 y_hat 的 shape 关系",
        "能解释 X.T @ residual 如何同时计算多个参数的梯度",
        "能从 feature scale 对照中判断训练稳定性变化"
      ]
    },
    {
      "id": "classification-metrics-and-leakage",
      "label": "实验：Binary Classification 的 Metrics 与 Data Leakage",
      "type": "experiment",
      "status": "completed",
      "parent": "numpy-ml-foundations",
      "learningRole": "primary-research-track",
      "goal": "在不平衡二分类中使用 baseline、confusion matrix 与正确的数据划分评估模型。",
      "summary": "完成 baseline 与 logistic classifier 对比，能用 confusion matrix、F1、validation threshold 和 train-only normalization 判断分类评估是否可信。",
      "readinessCriteria": [
        "能从 confusion matrix 判断 TP、FP、FN、TN",
        "能解释 accuracy 在不平衡数据中为何不足",
        "能说明 threshold 与 normalization statistics 只能在 train / validation 流程内决定"
      ]
    },
    {
      "id": "numpy-pandas-data-code-reading",
      "label": "课程：NumPy 与 Pandas 数据代码阅读",
      "type": "lesson",
      "status": "completed",
      "parent": "numpy-ml-foundations",
      "learningRole": "primary-research-track",
      "goal": "读懂科学 Python 中高频的 NumPy / Pandas 数据生成、选择、拼接、重排、聚合与表格检查代码。",
      "summary": "掌握常用数据操作的阅读地图，能追踪 X-y 对齐、axis 聚合、Pandas 类别统计、缺失值检查与填补。",
      "readinessCriteria": [
        "能追踪 X/y 的拼接、同步重排和对齐关系",
        "能说明 slice、column selection、boolean mask 与 axis 聚合的区别",
        "能检查 DataFrame 的列、dtype、类别分布、缺失值及 fillna 的结果"
      ]
    },
    {
      "id": "ml-workflow-evaluation",
      "label": "Machine Learning Workflow 与 Evaluation",
      "type": "topic",
      "status": "active",
      "parent": "ai-cv-foundations"
    },
    {
      "id": "sklearn-pipeline-cross-validation",
      "label": "实验：scikit-learn Pipeline、Cross-Validation 与 Holdout Test",
      "type": "experiment",
      "status": "completed",
      "parent": "ml-workflow-evaluation",
      "learningRole": "primary-research-track",
      "goal": "用 scikit-learn Pipeline 和 cross-validation 复现正确的训练、preprocessing、模型选择与最终 test workflow。",
      "summary": "完成 Pipeline/CV/holdout test 流程，理解 C 的逆正则化含义以及 C=0.001 的极端退化为 baseline 现象。",
      "readinessCriteria": [
        "能说明 Pipeline 如何在每个 CV training fold 内 fit scaler",
        "能说明 C 由 cross-validation 而不是 test 选择",
        "能报告 CV mean/std 与独立 test metrics 的不同作用"
      ]
    },
    {
      "id": "computing-skills",
      "label": "计算机技能体系",
      "type": "root",
      "status": "active"
    },
    {
      "id": "software-engineering-and-systems",
      "label": "软件工程与系统",
      "type": "track",
      "status": "active",
      "parent": "computing-skills"
    },
    {
      "id": "containerization",
      "label": "Containerization",
      "type": "topic",
      "status": "active",
      "parent": "software-engineering-and-systems"
    },
    {
      "id": "docker-containerization-foundations",
      "label": "Docker #1：入门实践",
      "type": "learning_track",
      "status": "completed",
      "parent": "containerization",
      "learningRole": "supporting-track",
      "goal": "通过容器、端口映射与 bind mount 实验，建立 Docker 的最小工作模型。",
      "summary": "完成容器隔离、端口访问和文件持久化实践，能区分 image、container 与 bind mount。",
      "readinessCriteria": [
        "能解释 image 与 container 的区别",
        "能解释端口映射 8080:80",
        "能解释 bind mount 或 volume 的持久化作用",
        "能读懂简单 Dockerfile 的关键指令",
        "能说明 Docker Compose 何时适合管理多个服务"
      ]
    },
    {
      "id": "docker-concepts-image-container",
      "label": "Image / Container / Dockerfile",
      "type": "concept",
      "status": "planned",
      "parent": "docker-containerization-foundations"
    },
    {
      "id": "docker-experiment-port-mapping",
      "label": "实验：端口映射",
      "type": "experiment",
      "status": "completed",
      "parent": "docker-containerization-foundations"
    },
    {
      "id": "docker-experiment-persistence",
      "label": "实验：文件挂载与持久化",
      "type": "experiment",
      "status": "completed",
      "parent": "docker-containerization-foundations"
    },
    {
      "id": "docker-compose-multi-service",
      "label": "Docker Compose 多服务编排",
      "type": "concept",
      "status": "deferred",
      "parent": "docker-containerization-foundations"
    }
  ]
} as const;
